language: python
python:
  - "3.9"
before_install:
  - chmod +x ./flaskapp/st.sh
install:
  - pip install -r requirements.txt
script:
  - cd flaskapp
  - ./st.sh
deploy:
  provider: heroku
  api_key:
    secure: "YOUR_ENCRYPTED_HEROKU_API_KEY"
  app: your-heroku-app-name
  on:
    branch: main